# -*- coding: utf-8 -*-
"""Gen AI Intro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13KSwOOVhMLxxJ3pLhBZqituoRiwxVJ12
"""

import math

num = float(input("Enter a number to find its square root: "))

if num < 0:
    print("Square root is not defined for negative numbers in real numbers.")
else:
    sqrt = math.sqrt(num)
    print(f"The square root of {num} is {sqrt}")

num1 = input("Enter the first number: ")
num2 = input("Enter the second number: ")

print(f"Before swapping: num1 = {num1}, num2 = {num2}")

num1, num2 = num2, num1

print(f"After swapping: num1 = {num1}, num2 = {num2}")

num = float(input("Enter a number: "))

if num > 0:
    print("The number is positive.")
elif num < 0:
    print("The number is negative.")
else:
    print("The number is zero.")

num = int(input("Enter an integer: "))

if num % 2 == 0:
    print(f"{num} is an even number.")
else:
    print(f"{num} is an odd number.")

# Program to find the factorial of a number

def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n-1)

num = int(input("Enter a non-negative integer to find its factorial: "))

if num < 0:
    print("Factorial is not defined for negative numbers.")
else:
    print(f"The factorial of {num} is {factorial(num)}")

# Program to check if a number is a palindrome

def is_palindrome(n):

    num_str = str(n)

    return num_str == num_str[::-1]

num = int(input("Enter an integer to check if it's a palindrome: "))

if is_palindrome(num):
    print(f"{num} is a palindrome.")
else:
    print(f"{num} is not a palindrome.")

data = [
    {'name': 'Charan', 'age': 30, 'city': 'Guntakal'},
    {'name': 'Varshith', 'age': 25, 'city': 'Kadapa'},
    {'name': 'Rahul', 'age': 35, 'city': 'Kurnool'}
]

print(data)

age_above_25 = []
for item in data:
    if item['age'] > 25:
        age_above_25.append(item)

print(age_above_25)